### ISSUE TITLE
Modded cave biomes spawning too infrequently

### ISSUE THREAD

**Issue by Beanthief** [Apollounknowndev/tectonic#128]
I am using Tectonic with Galosphere and the pink salt shrine/caves are spawning at a minimum of 20000 blocks away from 0,0. Normally, they spawn roughly 1500 blocks from spawn.

**Comment by Apollounknowndev** [comment]
Definitely too late on this but here's an explanation for anyone in the future seeing this:
Biomes based on the `erosion` noise will generate larger and more spaced out in Tectonic than in vanilla due to the way the mod is designed. This included vanilla's Deep Dark and Galosphere's Pink Salt Caves.

**Comment by GionaCantarutti** [comment]
Is there any solution to this? Deep Dark isn't hard to find in my experience but galosphere biomes are virtually not spawning, even the /locate command cannot find any

I'm using both tectonic and terralith
