### ISSUE TITLE
Question regarding Terralith/Tectonic compatibility

### ISSUE THREAD

**Issue by Marteinstr** [Apollounknowndev/tectonic#145]
Hi, sorry for the kinda unnecessary 'issue' i opened but i didn't find any other way to ask you this question:

So for compatibility's sake, using both tectonic and terralith as mods work. For datapacks, instead of using tectonic, terratectonic should be used to be compatible with the terralith datapack.

My question is about using terralith as datapack and tectonic as mod. Does this work? Or is it only working properly if both are of the same type (mod/mod or datapack/datapack)?

Thanks in advance!

**Comment by Tobias755** [comment]
I have the same question. I would like to play everything with mods, but unfortunately there is still no terralith mod update for 1.20.5 and 1.20.6, so I have to use Terralith as a datapack, because the datapack got the update. But the Terratonic datapack has gotten no update so far for 1.20.5 and 1.20.6, so it doesn't work together, what kinda sucks, because I really want to play 1.20.6 haha. It all takes its time, but yeah haha...

**Comment by Apollounknowndev** [comment]
You can't use Terralith as a datapack and Tectonic as a mod currently.

**Comment by Apollounknowndev** [comment]
Terratonic 1.20.5 should be working in datapack form fine, if it isn't then that's an issue I'll fix

**Comment by Tobias755** [comment]
Hey, but on Modrinth is no version higher than 1.20.4 or do you have it elsewhere for the download? I mean, I hope I'm not blind haha. Kind regards :)

**Comment by Apollounknowndev** [comment]
The 1.20.4 version should work fine on 1.20.5.

**Comment by Tobias755** [comment]
Yep, you're right. I wasn't expecting a 1.20.4 version to work with the latest updates. That's my bad. Thanks mate👍🏼
