### ISSUE TITLE
High RAM usage with Bumblezone

### ISSUE THREAD

**Issue by Apollounknowndev** [Apollounknowndev/tectonic#195]
Likely a density function issue. Yikes.

https://discord.com/channels/313125603924639766/1249305774987939900/1269130149161467905

**Comment by TheGameAce** [comment]
If you don't mind me popping in here, I was actually about to make a report regarding this after a few days of deliberating on whether or not to do so. For reference, I'm the user who made the initial report to Grunt who figured out the issue & made some adjustments to compensate, which seem to have done the trick (at least in regards to mostly stabilizing Tectonic + Bumblezone together). You have basically everything regarding the issue in the Github report for Bumblezone linked in there (including some Spark profiler results), but if it helps, I'd also add that it seems to cause some notable issues in the Overworld as well, and somewhat less notable issues in various other dimensions.

Memory use gets eaten up pretty badly beyond what I'd expect from a pack like mine while Tectonic is in play. I've noted world gen is extremely slow as well, and both issues started while initially putting the pack together right after I introduced Tectonic. Can make a separate issue for that if you'd like, since that (seemingly) goes beyond the scope of compatibility with Bumblezone. Could be an alternate source (I can only speculate either way based on observations; my capacity for reading Spark reports is quite limited), but between the timing and mod list, I can't imagine any other source as the issue.

Apologies if this isn't warranted or the appropriate place. Just wanted to throw that out there to try and get the issue dealt with.

**Comment by Apollounknowndev** [comment]
I've contained the issue to exclusively the Overworld in v2.4.1. I'll have to do some investigating into how to properly fix the issue, but for now removing the issue from other mod's dimensions is good enough for me.

**Comment by Apollounknowndev** [comment]
Fixed in v2.4.1 for both 1.20.1 and 1.21.
