### ISSUE TITLE
New updated (Forge v2.4.1) messes up worldgen

### ISSUE THREAD

**Issue by Subthy** [Apollounknowndev/tectonic#216]
Hello, 
So I just updated from v2.3.5a to v2.4.1 forge and it has messed up the terrain gen. If it was meant to happen, it would have been nice to have a disclaimer in changelogs.

![image](https://github.com/user-attachments/assets/1814c3a4-6ab8-4f27-92a2-cc2a6485ce56)

**Comment by Apollounknowndev** [comment]
Oh yikes, that wasn't supposed to happen

**Comment by Apollounknowndev** [comment]
Can't replicate, just tested loading a v2.3.5 world on v2.4.1 and nothing changed other than slight adjustments in swamps. Can you provide a mod list?

![2024-09-02_15 36 19](https://github.com/user-attachments/assets/fdd0aa79-0ff8-4003-99a1-39b1a34ef987)

**Comment by Subthy** [comment]
Hello, sure I can. https://www.curseforge.com/minecraft/modpacks/pokeasub/files/all?page=1&pageSize=20 Here is the modpack that I use. The most recent version has v2.3.5, but the one before has v.2.4.1, as I needed to downgrade, so I don't get more weird chunks. I tested if any of the other mods that I changed in the update did something, but no. I am guessing one of the mods is now incompatible with the latest version of Tectonic.

**Comment by Apollounknowndev** [comment]
I believe the issue here is the modpack using both Lithosphere and Tectonic. Both mods are complete overhauls of terrain shaping and shouldn't be used with one another. What I assume happened is that Tectonic 2.4 had some backend changes that altered how Lithosphere and Tectonic interact, causing chunk borders.

There's not really a good way to fix that other than staying on v2.3.5.

**Comment by Subthy** [comment]
Gotcha, thanks for help <3
