### ISSUE TITLE
[1.19.2, Forge] [Tectonic v2.3.5a] Multiple massive issues with the mod

### ISSUE THREAD

**Issue by RevontuletCXVII** [Apollounknowndev/tectonic#224]
The terrain it generates is awesome. The caves and rives and deeper oceans - beautiful. But it breaks so much stuff it's not worth keeping.

For starters, it causes initial world generation to take 10 times longer than it should - it also breaks new chunks rendering until leaving and rejoining the world and incorrectly generates new biomes and chunks causing massive walls to appear.

I've been trying to isolate the cause of my worldgen issues for a week hoping it wasn't Tectonic, but unfortunately it is.

Using with only Terralith.

**Comment by RevontuletCXVII** [comment]
After some more testing, it seems it's when Terralith and Tectonic are together (both as mods), they start misbehaving. Tectonic on its own is doing just fine, and even the BOP compat mod is behaving.

**Comment by Apollounknowndev** [comment]
Worldgen speed when stacking worldgen mods is an inevitable concern; Terralith and Terrablender each double loading times. Tectonic doesn't have much of an impact on its own.
Rendering issues wouldn't be caused by Tectonic but instead some other mod.

1.19.2 is also no longer a supported version, as maintaining it alongside all other versions became an increasing unsustainable task.
