### ISSUE TITLE
[1.20.1] Terrain generating under water level making transition rough

### ISSUE THREAD

**Issue by Matthysse** [Apollounknowndev/tectonic#56]
Hello!

I saw in a modded environnement this type of worldgen "errors" that appeared near rivers: the terrain seems not to transition normally to the water, making these rough edges between water and grass. It does sometimes appear in vanilla but way less I think : 

![2023-09-22_12 08 14](https://github.com/Apollounknowndev/tectonic/assets/32510957/5441ac7e-79df-4580-9c4d-8de40eb5bf1b)
![2023-09-22_12 07 55](https://github.com/Apollounknowndev/tectonic/assets/32510957/cbc88f51-605c-4e92-b79b-03c14dd60bf8)
![2023-09-22_12 07 44](https://github.com/Apollounknowndev/tectonic/assets/32510957/04baa669-b52a-41b3-967a-f780eaa47afc)

So I tried just using forge and the mod itself (without terrablender as it could interfer), and I get the same result : 

![2023-09-22_14 00 47](https://github.com/Apollounknowndev/tectonic/assets/32510957/9567a878-1b1e-4fd9-bdec-f14d7f3c6543)

**Comment by Apollounknowndev** [comment]
Can you give seed/coordinates for the images, if possible?

**Comment by NanoGalacticHasNeverBeenTakenBeforewtf** [comment]
I've been coming across this issue in the 1.20-2.3.1a version (running 1.20.1), using fabric. I've seen this issue in some other terrain/biome mods without Tectonic, but happens more and more extreme using Tectonic. I tried setting the terrain_scale to 0.0 in the config, but in that makes the terrain extremely glitched out, and this issue is pretty much the only thing you see and to the extreme. I also tried 1.0 and 2.0, in both cases this issue is present, though in 2.0 it appears to be less.

On the default (1.25), it's quite easy to find if you follow along a plains coastline or river for a minute. It's also most easily noticeable in swamps.

**Comment by BrewingCoder** [comment]
I came here to report this same issue with 2.3.4a/Forge.

I am trying to reduce the overall noise of worldgen and get a more flat (but not a flat world) generation for MineColonies.

When I move the "terrain_scale" setting below 60 I see this.   The rest of the worldgen looks great but the biome edges for plains are being taken below sea level.
![image](https://github.com/user-attachments/assets/dfee29c4-bea0-49aa-ab42-e568633412e4)

**Comment by BrewingCoder** [comment]
FYI This only seems to affect Plains Biomes right now though I'll keep searching.  So far Forests, Beaches, Hills, etc. seem to be fine. 

Only a plains that drops right to water does this.

**Comment by Apollounknowndev** [comment]
Finally found the issue and patched it, will be fixed in the next release.

**Comment by Apollounknowndev** [comment]
Fixed in v2.4.1 for both 1.20.1 and 1.21.
