### ISSUE TITLE
Incorrect geode and ocean moument generation

### ISSUE THREAD

**Issue by SuggestionMan** [Apollounknowndev/tectonic#82]
I created a world with this datapack, and went exploring the oceans. Though really nice from the aspect of terrain generation,
I noticed two issues. First, as the oceans are deeper, several geodes are exposed on the ocean floor in the deepslate
layer, which I personally think is not something fit for oceans. Perhaps there is a way to fix it? And the second, near my spawnpoint, 4 ocean monuments generated near each other; for comparison I have never encountered such generation in vanilla Minecraft. Could it be something that the datapack is responsible for?

![2024-01-17_15 25 31](https://github.com/Apollounknowndev/tectonic/assets/93024605/dd8c7669-d467-4580-8648-c23cb1cd74eb)
**Geode generation ^**

![2024-01-17_15 22 03](https://github.com/Apollounknowndev/tectonic/assets/93024605/be22333d-1b5f-488a-848a-af713ec5be25)
**Four ocean monuments near world spawnpoint at once ^**

**Comment by Apollounknowndev** [comment]
- Ocean monuments generate that closely together in vanilla, it just appears more prevalent in Tectonic because oceans are much larger and emptier.
- Geode generation is unintended but likely will not be fixed as it'd require messing with geode placement and I'd like to avoid touching feature placement if possible.
